# Generated by Django 4.2.4 on 2023-09-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.CharField(help_text='Cat image id. example: eOLpJytrbsQ', max_length=200, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(help_text='Image download link. example: http://unsplash.com/photos/eOLpJytrbsQ/download', max_length=800)),
                ('rank', models.PositiveIntegerField(blank=True, help_text='current rank of the cat compared to others', null=True)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
