# Generated by Django 4.2.4 on 2023-09-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatTopChart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='also can be used for tracking api responses')),
                ('per_page', models.IntegerField(help_text='request size')),
                ('page', models.PositiveIntegerField(help_text='request page')),
            ],
        ),
        migrations.AlterField(
            model_name='cat',
            name='link',
            field=models.SlugField(help_text='Image download link. example: https://unsplash.com/photos/eOLpJytrbsQ/download', max_length=800),
        ),
        migrations.AlterField(
            model_name='cat',
            name='points',
            field=models.IntegerField(default=0, help_text='are based on user likes and dislikes'),
        ),
    ]
