# Generated by Django 4.2.4 on 2023-09-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatTopChart', '0002_catrequest_alter_cat_link_alter_cat_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='catrequest',
            name='successful_additions',
            field=models.PositiveIntegerField(default=0, help_text='how many cats was added successfully'),
        ),
    ]
