# Generated by Django 4.2.4 on 2023-09-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatTopChart', '0002_alter_cat_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='rank',
            field=models.PositiveIntegerField(blank=True, help_text='current rank of the cat compared to others', null=True),
        ),
    ]
