# Generated by Django 4.2.4 on 2023-09-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatTopChart', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='disliked_cats',
            field=models.ManyToManyField(blank=True, related_name='cat_disliked', to='CatTopChart.cat'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='liked_cats',
            field=models.ManyToManyField(blank=True, related_name='cat_liked', to='CatTopChart.cat'),
        ),
    ]
