# Generated by Django 4.2.4 on 2023-09-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0, help_text='depends'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.PositiveIntegerField(blank=True, help_text='current rank of the user compared to others', null=True),
        ),
    ]
