# Generated by Django 4.2.4 on 2023-09-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_user_customuser_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0, help_text='depends on nuber of rated cats'),
        ),
    ]
